version: "2"
volumes:
    pihole_config_dir:
    dnsmasq_config_dir:
    config:
services:
  homeassistant:
    build: homeassistant
    ports:
      - 80:8123
    privileged: true
    volumes:
      - "config:/config"
    restart: always
    devices:
      - "/dev:/dev"
      - "/dev/serial/by-id/usb-0658_0200-if00:/dev/zwave"
    environment:
      - TZ="Europe/Copenhagen"
  hass-configurator:
    image: "causticlab/hass-configurator-docker:arm"
    restart: always
    volumes:
      - "config:/hass-config"
    environment:
      - HC_BASEPATH=/hass-config
  influxdb:
    restart: always
    build: ./influxdb
    volumes:
      - "config:/data"
  grafana:
    restart: always
    build: ./grafana
    ports:
      - "8081"
    volumes:
      - "config:/data"
    environment:
      - "GF_SERVER_HTTP_PORT=8081"
      - "GF_PATHS_PROVISIONING=/usr/src/app/provisioning"
      - "GF_SESSION_PROVIDER=memory"
  sensor:
    build: ./sensor
    privileged: true
    restart: always
    volumes:
      - "config:/data"
  telegraf:
    build: ./telegraf
    restart: always
    cap_add:
      - SYS_ADMIN
  mqtt:
    image: arm32v6/eclipse-mosquitto
    ports:
      - "1883:1883"
    restart: always
  automation-api:
    image: nkuik89/automation-api:latest
    ports:
      - "8000:8080"
    restart: always
  pihole:
    restart: always
    build: ./pihole
    privileged: true
    volumes:
      - "pihole_config_dir:/etc/pihole"
      - "dnsmasq_config_dir:/etc/dnsmasq.d"
    dns:
      - "127.0.0.1"
      - "1.1.1.1"
    environment:
      DNSMASQ_LISTENING: eth0
      INTERFACE: eth0
      DNS1: 127.0.0.1#5053
      WEB_PORT: 8090
    ports:
      - "8090:8090"
    network_mode: host
    labels:
      io.balena.features.dbus: "1"
  # https://hub.docker.com/r/klutchell/unbound-dnscrypt
  unbound:
    build: ./unbound
    ports:
      - "5053:5053/udp"
