cast:
  media_player:
    - host: 192.168.86.182

sonos:
  media_player:
    hosts:
      - 192.168.86.182

spotify:
  client_id: !env_var SPOTIFY_ID 
  client_secret: !env_var SPOTIFY_TOKEN

####################################################
#                                                  #
#                Default Config                    #
#                                                  #
####################################################
# https://www.home-assistant.io/integrations/default_config/
# Configure a default setup of Home Assistant (frontend, api, etc)
#default_config:
person:
updater:
zone:
zeroconf:
system_health:
sun:
ssdp:
map:
logbook:
config:
history:
logger:
  default: info

####################################################
#                                                  #
#                   CUSTOMIZING                    #
#                                                  #
####################################################
# https://www.home-assistant.io/docs/configuration/customizing-devices/
#https://home-assistant.io/docs/configuration/basic/
homeassistant:
  auth_providers: 
   - type: homeassistant
   #- type: legacy_api_password
   - type: trusted_networks
     trusted_networks:
       - 127.0.0.1
       - ::1
       - fd00::/8
  temperature_unit: C
  name: Home
  unit_system: metric
  time_zone: Europe/Copenhagen
  external_url: !env_var HOMEASSISTANT_EXTERNAL_URL 
  # customize: !include customize.yaml
  # customize_glob: !include customize_glob.yaml
  # packages: !include_dir_named packages
  # whitelist_external_dirs:
  #   - /config

####################################################
#                                                  #
#                     HTTP                         #
#                                                  #
####################################################
# https://www.home-assistant.io/integrations/http/
http:
  #base_url: https://nomescelto.duckdns.org:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: True
  login_attempts_threshold: 5

####################################################
#                                                  #
#                     TTS                          #
#                                                  #
####################################################
# https://www.home-assistant.io/integrations/tts/
# Text to speech
tts:
  - platform: google_translate

####################################################
#                                                  #
#                  Groups                          #
#                                                  #
####################################################
# https://www.home-assistant.io/integrations/mobile_app/
# group: !include groups.yaml

####################################################
#                                                  #
#                  Automations                     #
#                                                  #
####################################################
# https://www.home-assistant.io/integrations/automation/
# automation: !include automations.yaml

####################################################
#                                                  #
#                  Scripts                         #
#                                                  #
####################################################
# https://www.home-assistant.io/integrations/script/
# script: !include scripts.yaml

####################################################
#                                                  #
#                   Scene                          #
#                                                  #
####################################################
# https://www.home-assistant.io/integrations/scene/
# scene: !include scenes.yaml


####################################################
#                                                  #
#                  Mobile APP                      #
#                                                  #
####################################################
# https://www.home-assistant.io/integrations/mobile_app/
mobile_app:

####################################################
#                  Dev Tracker                     #
#                                                  #
#                                                  #
####################################################
# https://www.home-assistant.io/integrations/device_tracker/
# device_tracker: !include device_tracker.yaml

####################################################
#                  Dev Tracker                     #
#                   Owntracks                      #
#                                                  #
####################################################
# https://www.home-assistant.io/integrations/owntracks/
# Disable cause enabled in Integrations
# owntracks:
#   max_gps_accuracy: 200

####################################################
#                                                  #
#                   Camera                         #
#                                                  #
####################################################
# https://www.home-assistant.io/integrations/camera/
# camera: !include camera.yaml

####################################################
#                                                  #
#                   MQTT                           #
#                                                  #
####################################################
# https://www.home-assistant.io/integrations/mqtt/
mqtt:  
  broker: mqtt

####################################################
#                                                  #
#               Frontend/Themes                    #
#                                                  #
####################################################
frontend:
  extra_module_url:
    - /hacsfiles/custom-sidebar/custom-sidebar.js
  #themes: !include themes.yaml
  themes: !include_dir_merge_named themes


####################################################
#                                                  #
#              Input Slider and Boolean            #
#                                                  #
####################################################

#input_boolean: !include_dir_merge_named input_boolean
# input_select: !include_dir_merge_named input_select
# input_number: !include_dir_merge_named input_number

# notify: !include notify.yaml
# telegram_bot:
#    - platform: polling
#      api_key: !secret telegram_apikey
#      #trusted_networks:
#       #- 149.154.167.197/32
#       #- 149.154.167.198/31
#       #- 149.154.167.200/29
#       #- 149.154.167.208/28
#       #- 149.154.167.224/29
#       #- 149.154.167.232/31
#      allowed_chat_ids:
#        - !secret telegram_clientid
#        - !secret telegram_clientid2

sensor: !include sensors.yaml


####################################################
#                                                  #
#                     ALEXA                        #
#                                                  #
####################################################
# alexa_media:
#   accounts:
#     - email: !secret amazonemail
#       password: !secret amazonpwd
#       #url: !secret amazonurl
#       url: !secret amazonurl_it
#       scan_interval: 30
      #debug: true
      #exclude_devices:
      #- "This Device"
      #- "nicolo's Alexa Apps"
      #- "nicolo's bose home speaker 500"
      #- "echo dot di nicolo"
      #- "salotto"


####################################################
#                                                  #
#             Lovelace/CustomUpdater               #
#                                                  #
####################################################

#https://www.home-assistant.io/lovelace/yaml-mode/
lovelace:
  mode: yaml
  resources:
    - url: /local/monster-card.js   
      type: js 
    - url: /local/custom-lovelace/weather-card/weather-card.js 
      type: module 
    - url: /local/plugins/card-tools.js
      type: js
    - url: /hacsfiles/plan-coordinates/plan-coordinates.js 
      type: js   
    - url: /hacsfiles/atomic_calendar/atomic_calendar.js     
      type: module
    - url: /hacsfiles/atomic-calendar-revive/atomic-calendar-revive.js     
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module 
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js 
      type: module
    - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
      type: module
    - url: /hacsfiles/fitbit-card/fitbit-card.js
      type: js
    - url: /hacsfiles/secondaryinfo-entity-row/secondaryinfo-entity-row.js 
      type: module 
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js  
      type: module
    - url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js
      type: module
    - url: /hacsfiles/lovelace-card-tools/card-tools.js  
      type: module     
    - url: /hacsfiles/unused-card/unused-card.js
      type: module
    - url:  /hacsfiles/shutter-cover-panel-card/shutter-cover-panel-card.js
      type: module
    - url: /hacsfiles/LG-WebOS-Remote-Control/lg-remote-control.js
      type: module
    - url: /hacsfiles/LG-Keypad/card-numeric-pad.js
      type: module
    - url: /hacsfiles/canvas-gauge-card/canvas-gauge-card.js
      type: module
    - url: /hacsfiles/custom-header/custom-header.js
      type: module
    - url: /hacsfiles/logbook-card/logbook-card.js
      type: module
    - url: /hacsfiles/username-element/username-element.js
      type: module
    - url: /hacsfiles/weather-card/weather-card.js
      type: module
    - url: /hacsfiles/custom-sidebar/custom-sidebar.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module


# switch: !include switch.yaml
# binary_sensor: !include binary_sensors.yaml

####################################################
#                                                  #
#                   SPEEDTEST                      #
#                                                  #
####################################################

#https://www.home-assistant.io/components/speedtestdotnet/
speedtestdotnet:
  server_id: 19217 # server Copenhagen
  scan_interval:
    hours: 4
  monitored_conditions:
    - ping
    - download
    - upload

####################################################
#                                                  #
#                 Media player                     #
#                                                  #
####################################################
# https://www.home-assistant.io/integrations/media_player/
# https://www.home-assistant.io/integrations/universal/
# https://www.home-assistant.io/integrations/androidtv/

# media_player: !include media_player.yaml

####################################################
#                                                  #
#                 Shell Commands                   #
#                                                  #
####################################################
# https://www.home-assistant.io/integrations/shell_command/

# shell_command: !include shell_commands.yaml

####################################################
#                    Alexa                         #
#               Smart Home Speakers                #
#             Powered by Haaska Skill              #
####################################################
#### API ALEXA ###
# api:
#  alexa:
#    smart_home:

####################################################
#                                                  #
#                    Wake on LAN                   #
#                                                  #
####################################################
# https://www.home-assistant.io/integrations/wake_on_lan/

wake_on_lan:

####################################################
#                                                  #
#                      Google                      #
#                     Calendar                     #
####################################################
# https://www.home-assistant.io/integrations/calendar.google/

# google:
#   client_id: !secret google_clientid
#   client_secret: !secret google_secret


####################################################
#                                                  #
#                      Alarm                       #
#                      Panel                       #
####################################################
# https://www.home-assistant.io/integrations/manual/

# alarm_control_panel:
#   - platform: manual
#     name: Home Alarm
#     code: '1234'
#     arming_time: 30
#     delay_time: 20
#     trigger_time: 4
#     disarmed:
#       trigger_time: 0
#     armed_home:
#       arming_time: 0
#       delay_time: 0
